language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

script:
# Build
  - cd projects/cmake
  - ./build.sh
# Run tests
  - cd ../..
  - echo "\"Hello World\"" | projects/cmake/rb
  - cd tests
  - ./run_integration_tests.sh
# Run testiphy
  - export PATH=${TRAVIS_BUILD_DIR}/projects/cmake:$PATH
  - echo "outputPrecision=15" > ~/.RevBayes.ini
  - cd
  - git clone https://gitlab.com/testiphy/testiphy.git
  - cd testiphy
  - ./testiphy rb

# notifications
notifications:
  slack: revbayes:bQO6VTun0Orhx2NiKktVPDsS
